compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

enableMirror: true

enableOfflineMode: true

enableTelemetry: false

nodeLinker: pnp

supportedArchitectures:
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
