name: .Pre

on:
  workflow_call:

jobs:

  printenv:
    name: Print Environment
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: print
        run: | 
          echo "Repository name: $GITHUB_REPOSITORY"
          echo "Commit sha: $GITHUB_SHA"
          echo "Branch name: $GITHUB_REF"
          echo "Workflow name: $GITHUB_WORKFLOW"
          echo "Workflow Initiator: $GITHUB_ACTOR"
          echo "Github workspace: $GITHUB_WORKSPACE"
          CACHE_LIST=$(gh cache list --json ref)
          if [[ "$CACHE_LIST" == *"$GITHUB_REF"* ]]; then
            echo "The cache includes $GITHUB_REF"
          else
            echo "The cache does not include $GITHUB_REF"
          fi
        shell: bash

  check:
    name: Check Cache
    runs-on: ubuntu-latest
    outputs:
      should-pull: ${{ steps.check.outputs.should-pull }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: check cache
        id: check
        run: | 
          CACHE_LIST=$(gh cache list)
          if [[ "$CACHE_LIST" == *"$GITHUB_REF"* ]]; then
            # echo "$CACHE_LIST" | awk 'NR==1{print $1}'
            echo "Cache already exists. Skipping dependencies"
            echo "should-pull=false" >> $GITHUB_OUTPUT
          else 
            echo "should-pull=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

  dependencies:
    name: Pull Dependencies
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.should-pull == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - name: Clean Yarn cache
        run: yarn cache clean
      - name: Install dependencies
        run: yarn
  