name: .Pre

on:
  workflow_call:

jobs:
  dependencies:
    name: Pull Dependencies
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: print cache
        run: gh cache list
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - name: Install dependencies
        run: yarn
  