name: Pull Request

on:
  workflow_call:
  # pull_request:
  #   branches: [main]

jobs:
  dependencies:
    name: Pull Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Environment
        run: |
          printenv | grep 'sbl_'
        shell: bash
      - uses: ./.github/actions/setvars
      - name: Print Environment
        run: |
          printenv | grep 'sbl_'
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Clean Yarn cache
        run: yarn cache clean
      - name: Install dependencies
        run: yarn
  