name: BuildImage

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        id: checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: version
        run: |
          echo "TAG_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: 'Build Image'
        id: build
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/sbl-frontend:latest -f Dockerfile .
          docker tag ghcr.io/cfpb/regtech/sbl/sbl-frontend:latest ghcr.io/cfpb/regtech/sbl/sbl-frontend:${{env.TAG_VERSION}}
          docker tag ghcr.io/cfpb/regtech/sbl/sbl-frontend:latest ghcr.io/cfpb/regtech/sbl/sbl-frontend:${{env.TAG_VERSION}}_${{github.run_number}}.${{github.run_attempt}}

      - name: 'Login to GitHub Container Registry'
        id: login
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main' && steps.build.conclusion == 'success'
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Publish Image'
        id: publish
        if: github.ref == 'refs/heads/main' && steps.login.conclusion == 'success'
        run: |
          docker push ghcr.io/cfpb/regtech/sbl/sbl-frontend --all-tags

