name: Push

on:
  push:
    branches: [main]

jobs:
  call-pre:
    name: .Pre
    uses: ./.github/workflows/.pre.yml

  call-lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: call-pre

  call-build:
    name: Build
    if: ${{ always() }}
    uses: ./.github/workflows/build.yml
    needs: call-test

  call-test:
    name: Test
    if: ${{ always() }}
    uses: ./.github/workflows/test.yml
    needs: call-lint
    with:
      use_release_images: true

  call-codeql:
    name: CodeQL
    if: ${{ always() }}
    uses: ./.github/workflows/codeql.yml
    needs: call-lint
  
