name: Test

on:
  workflow_call:
  
jobs:
  # react:
  #   name: React
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setvars
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'yarn'
  #         cache-dependency-path: ./yarn.lock
      
  #     - name: Install dependencies
  #       run: yarn

  #     - name: Run React tests
  #       run: yarn test:ci

  # cypress:
  #   name: Cypress
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setvars
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'yarn'
  #         cache-dependency-path: ./yarn.lock

  #     - name: Install dependencies
  #       run: yarn

  #     - name: Run React tests
  #       run: yarn test:e2e:ci

  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/checkout@v4
      #   with:
      #     repository: 'cfpb/regtech-cleanup-api'
      # - uses: actions/checkout@v4
      #   with:
      #     repository: 'cfpb/regtech-mail-api'
      # - uses: actions/checkout@v4
      #   with:
      #     repository: 'cfpb/regtech-user-fi-management'
      # - uses: actions/checkout@v4
      #   with:
      #     repository: 'cfpb/sbl-filing-api'
      - uses: actions/checkout@v4
        with:
          repository: 'cfpb/sbl-project'
      - name: Check Current Path
        run: ls -alh
      - name: Check Root Path
        run: cd ../ && ls -alh
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      #     cache: 'yarn'
      #     cache-dependency-path: ./yarn.lock

      # - name: Install dependencies
      #   run: yarn
