name: Test

on:
  workflow_call:
  
jobs:
  # react:
  #   name: React
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setvars
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'yarn'
  #         cache-dependency-path: ./yarn.lock
      
  #     - name: Install dependencies
  #       run: yarn

  #     - name: Run React tests
  #       run: yarn test:ci

  # cypress:
  #   name: Cypress
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setvars
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'yarn'
  #         cache-dependency-path: ./yarn.lock

  #     - name: Install dependencies
  #       run: yarn

  #     - name: Run React tests
  #       run: yarn test:e2e:ci

  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'sbl-frontend'
      - uses: actions/checkout@v4
        with:
          repository: 'cfpb/regtech-cleanup-api'
          path: 'regtech-cleanup-api'
      - uses: actions/checkout@v4
        with:
          repository: 'cfpb/regtech-mail-api'
          path: 'regtech-mail-api'
      - uses: actions/checkout@v4
        with:
          repository: 'cfpb/regtech-user-fi-management'
          path: 'regtech-user-fi-management'
      - uses: actions/checkout@v4
        with:
          repository: 'cfpb/sbl-filing-api'
          path: 'sbl-filing-api'
      - uses: actions/checkout@v4
        with:
          repository: 'cfpb/sbl-project'
          path: 'sbl-project'

      - name: Build Frontend
        run: |
          cd sbl-frontend
          docker build -t sbl-project-frontend .
      - name: Build Cleanup API
        run: |
          cd regtech-cleanup-api
          docker build -t sbl-project-cleanup .
      - name: Build Mail API
        run: |
          cd regtech-mail-api
          docker build -t sbl-project-mail-api .
      - name: Build User Fi API
        run: |
          cd regtech-user-fi-management
          docker build -t sbl-project-user-fi .
      - name: Build Filing API
        run: |
          cd sbl-filing-api
          docker build -t sbl-project-filing .

      # - name: Check Current Path
      #   run: pwd && ls -alh
      # - name: Check Repo Paths
      #   run: |
      #     ls -alh sbl-project
      #     ls -alh sbl-frontend
      #     ls -alh sbl-filing-api
      #     ls -alh regtech-mail-api
      #     ls -alh regtech-user-fi-management
      #     ls -alh regtech-cleanup-api

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ./sbl-frontend/yarn.lock

      - name: Install Yarn Dependencies
        run: | 
          cd sbl-frontend
          yarn
          yarn playwright install --with-deps

      - name: Standup Stack
        run: |
          cd sbl-project
          docker compose --profile="backend" --profile="frontend" up -d --remove-orphans --build
      
      # - name: Sleep
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '60s'

      - name: Check running containers
        run: docker ps

      - name: Run Playwright Tests
        run: |
          cd sbl-frontend
          cat .env.example.public > ./.env
          cat .env.example.private >> ./.env
          yarn playwright test --workers 4