name: Test

on:
  workflow_call:
  
jobs:
  react:
    name: React
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      
      - name: Install dependencies
        run: yarn

      - name: Run React tests
        run: yarn test:ci

  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock

      - name: Install dependencies
        run: yarn

      - name: Run React tests
        run: yarn test:e2e:ci
