name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  React:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Run React tests
        run: yarn test:ci
  Cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Run React tests
        run: yarn test:e2e:headless
